products/nativescript/tns.py
products/nativescript/tns_assert.py
products/nativescript/tns_helpers.py
tests/cli/create/create_tests.py

Refactor:
- Tests in create_tests.py
Fix:
- Verifications for created app in `tns_assert.py`

refactor: create tests

---

.pylintrc
products/nativescript/tns.py
products/nativescript/tns_assert.py
tests/cli/test/test.md
tests/cli/test/test_test.py

Re write old tests for tns test command.
Old tests:
https://github.com/NativeScript/nativescript-cli-tests/blob/master/tests/emulator/unittests_tests.py
https://github.com/NativeScript/nativescript-cli-tests/blob/master/tests/simulator/unittests_tests.py

feat: tests for tns test command

---

tests/cli/create/test_init.py

Re-write `tns init` and `tns install` tests.

feat: rewrite init tests

---

data/templates.py
products/nativescript/tns_logs.py
products/nativescript/tns_paths.py
tests/templates/template_tests.py

Add tests for enterprise templates.

feat: tests for enterprise templates

---

.gitignore
assets/logs/hello-world-ng/items.component.ts
data/sync/hello_world_ng.py
products/nativescript/tns_logs.py
tests/cli/run/templates/hello_world_ng_tests.py

added new console logs for angular apps

feature: angular console logs

---

products/nativescript/tns.py

added:
plugin_add and plugin_remove

feat: plugin add and remove

---

products/nativescript/preview_helpers.py

fix: run preview method

---

core/utils/device/adb.py
data/sync/hello_world_js.py
data/sync/hello_world_ng.py
products/nativescript/preview_helpers.py
products/nativescript/tns_logs.py
tests/cli/preview/templates/hello_word_js_tests.py
tests/cli/preview/templates/hello_word_ng_tests.py

feat: test for preview with NG

---

core/utils/file_utils.py

On Windows we use Python3, it throws different kind of exceptions when delete folder fails.

fix: schematics tests on Windows

---

tests/cli/device/test_deploy_and_device.py

Address comments in https://github.com/NativeScript/nativescript-tooling-qa/pull/75

chore: address feedback to #75

---

core/base_test/tns_test.py
core/settings/Settings.py
core/utils/device/adb.py
data/sync/hello_world_js.py
data/sync/hello_world_ng.py
tests/cli/preview/templates/hello_word_js_tests.py

Migrate the rest of the preview tests. 
Test on two emulators, emulator and simulator, test plugin warnings

feat: add more preview tests

---

assets/runtime/android/files/android-runtime-961/main-page.js
assets/runtime/android/files/android-runtime-961/main-view-model.js
assets/runtime/android/files/android-runtime-961/package.json
requirements.txt
requirements_darwin.txt
tests/runtimes/android/android_runtime_tests.py

Add test for arm64-V8 default build. Add test for android new date work when changing timezone.

Add Android Runtime tests.

---

assets/runtime/android/files/android-runtime-1286/webpack.config.js
tests/runtimes/android/sbg_tests.py

Add test for https://github.com/NativeScript/android-runtime/issues/1286

feat: add test for android issue 1286

---

products/nativescript/app.py

Update nativescript-vue to latest by default.

chore: update nativescript-vue to latest by default

---

tests/runtimes/android/android_runtime_tests.py

Add test for updating of tns-core-modules works correctly if you have build the app first.

Add test for updating tns-core-modules works correctly if you have build the app first.

---

tests/runtimes/android/sbg_tests.py

feat: add test for sbg

---

tests/runtimes/ios/ios_runtime_tests.py

Remove failing tests for an issue.

Fix: remove failing tests for an issue.

---

data/changes.py

Double parenthesis in data\changes.py", line 138 are causing failures with python 3 (Windows runs)

fix: failing tests

---

assets/runtime/ios/files/ios-runtime-1130/main-page.xml
tests/runtimes/ios/ios_runtime_tests.py

test for [ios-runtime issue#1130](https://github.com/NativeScript/ios-runtime/issues/1130) that checks

feat: ios-runtime issue 1130 - unicode chars

---

assets/runtime/android/files/android-runtime-1286/webpack.config.js
tests/runtimes/android/sbg_tests.py

`webpack.config.js` file used in the test needs to be updated due to changes in it that lead to failure  of `tns build android` with 
```
Error: Cannot find module 'uglifyjs-webpack-plugin'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
...
```

fix: update webpack config file

---

assets/runtime/android/files/android-runtime-1347/AndroidManifest.xml
assets/runtime/android/files/android-runtime-1347/main-page.js
assets/runtime/android/files/android-runtime-1347/main-view-model.js
assets/runtime/android/files/android-runtime-1347/not_sticky/app.js
assets/runtime/android/files/android-runtime-1347/sticky/app.js
assets/runtime/android/files/android-runtime-1347/webpack.config.js
core/utils/device/adb.py
core/utils/file_utils.py
core_tests/e2e/core/adb_tests.py
core_tests/e2e/core/file_utils_tests.py
tests/runtimes/android/android_runtime_tests.py

Add tests for sticky and not_sticky foreground services. Add tests for core changes.

Add tests for sticky and not_sticky foreground services.

---

assets/runtime/ios/files/ios-runtime-1131/main-page.js
assets/runtime/ios/files/ios-runtime-1131/src/SwiftClass.swift
tests/runtimes/ios/ios_runtime_tests.py

Add test for issue https://github.com/NativeScript/ios-runtime/issues/1131

feat: add test for adding swift files

---

assets/runtime/android/files/android-runtime-1195/app.gradle
assets/runtime/android/files/android-runtime-1347/not_sticky/app.js
tests/runtimes/android/android_runtime_tests.py

Fix failing tests for missing native library namespace and typo in service type.

Fix failing tests for missing native library namespace and typo in service type.

---

tests/runtimes/android/error_activity_tests.py

Fix failing tests for error activity tests.

Fix: failing tests for error activity tests.

---

tests/runtimes/android/error_activity_tests.py

Change the wait logic for logs in error activity tests.

Change the wait logic for logs in error activity tests.

---

assets/runtime/android/files/android-runtime-1368/package.json
tests/runtimes/android/android_runtime_tests.py

Add test for useV8Symbols flag.

Add test for useV8Symbols flag.

---

assets/runtime/android/files/android-runtime-1347/without_oncreate_method/app.js
tests/runtimes/android/android_runtime_tests.py
tests/runtimes/android/android_service_tests.py

- Add test for service without implementing oncrate method
- Separate tests for services
- Add assert for app is running for builds with useV8Symbols flag

Add test for service without implementing oncrate method. Also separate tests for services.

---

assets/runtime/ios/files/ios-runtime-1120/main-page.js
tests/runtimes/ios/ios_runtime_tests.py

test for https://github.com/NativeScript/ios-runtime/issues/1120

feat: add test for ios issue 1120 - wrong returned internal class name

---

tests/runtimes/android/android_runtime_tests.py

Add test for ES6.

---

tests/cli/debug/test_debug_network_app.py

Changed app under tests, so we need also to change lines we break.

fix: debug tests

---

tests/cli/debug/test_debug_network_app.py

Do not check http request size, it is different of different machines.

chore: do not check request size

---

tests/perf/data.json
tests/perf/tooling/build_perf_tests.py

Do not measure prepare and build time without bundle.
Update perf values to match actual.

chore: test build time only with bundle

---

data/changes.py
data/const.py
data/sync/hello_world_js.py
products/nativescript/tns.py
products/nativescript/tns_logs.py
tests/cli/run/run_tests.py

Test for run command with different options: clean, justLaunch, syncAllFiles.....

feat: run tests

---

assets/runtime/ios/files/ios-runtime-843/app.component.ts
tests/runtimes/ios/ios_runtime_tests.py

- update log that is changed because of tests running with bundle
- update check in test that is more correct
- update file nativescript-dev-webpack/issues/903

fix: update ios tests

---

tests/code_sharing/ng_new_tests.py

Update webpack in schematics tests.

chore: update webpack in schematics tests

---

core/base_test/tns_test.py
core/utils/file_utils.py
core_tests/e2e/core/test_adb.py
core_tests/e2e/core/test_file_utils.py
core_tests/e2e/products/test_tns.py
core_tests/unit/utils/run_tests.py
run_common.py

- Fix and refactor e2e tests.
- Refactor File.download() method.
- Add option to clone templates from branch.

fix: e2e tests

---

tests/runtimes/ios/ios_runtime_tests.py

Increase time for ios test_391_tns_run_ios_console_time

Increase time for ios test_391_tns_run_ios_console_time

---

assets/issues/nativescript-cli-4343/src/TestClass2.h
assets/issues/nativescript-cli-4343/src/TestClass2.m
assets/issues/nativescript-cli-4343/src/module.modulemap
tests/cli/run/tests/run_tests.py

Fix permission denied error when copy/paste on android emulator api28. 
Fix ios test failing because of duplicated class name.

fix: fixes failing run tests

---

tests/code_sharing/migrate_web_tests.py

Ignore tests because of https://github.com/NativeScript/nativescript-schematics/issues/213

chore: ignore failing schematics tests

---

assets/runtime/ios/files/ios-pr-1144/main-page.js
tests/runtimes/ios/ios_runtime_tests.py

check callstacks are shown
https://github.com/NativeScript/ios-runtime/commit/6ec5d5c

feat: ios-runtime test for native and js callstacks issue

---

tests/runtimes/android/abi_split_with_snapshot_tests.py

Fix abi split tests.

---

assets/runtime/android/files/android-runtime-1347/not_sticky/app.js
assets/runtime/android/files/android-runtime-1347/sticky/app.js
assets/runtime/android/files/android-runtime-1347/without_oncreate_method/app.js

Fix android runtime service test for androidx.

Fix android runtime service test for androidx.

---

data/sync/master_detail_vue.py
tests/cli/platform/platform_tests.py

1. Increase timeout for vue master detail tests
2. Fix platform list test -  don't add ios platform on non osx runs

fix: fix failing tests

---

tests/runtimes/android/android_runtime_tests.py

Add test for removing buffer warning.

Add test for removing buffer warning.

---

tests/runtimes/android/android_runtime_tests.py

Add test for removing warnings from builds.

Add test for removing warnings from builds.

---

tests/runtimes/ios/ios_runtime_tests.py

since CLI made changes in logging

fix: update ios log assertions

---

data/sync/plugin_src.py

Added App.update method in order to update the app with the proper packages of dependencies, given in the build job parameters.

Add update app method to update demos with @next versions of deps

---

assets/runtime/android/files/android-runtime-1119/app.js
assets/runtime/android/files/android-runtime-1359/main-view-model.js
tests/runtimes/android/android_runtime_tests.py

Add test for android runtime issue 1354 and 1359. Fix tests caused by bundle.

Add test for android runtime issue 1354 and 1359. Fix tests caused by bundle.

---

assets/runtime/android/files/android-runtime-1409/new/package.json
assets/runtime/android/files/android-runtime-1409/package.json
tests/runtimes/android/sbg_tests.py

Add test for "SBG fails when 'nativescript' property in package.json is not an object https://github.com/NativeScript/android-runtime/issues/1409

add sbg test for nativescript property in package.json

---

assets/runtime/ios/files/ios-runtime-921/special-value/main-view-model.js
assets/runtime/ios/files/ios-runtime-921/toHexString-and-toDecimalString/main-view-model.js
assets/runtime/ios/files/ios-runtime-921/wrapped-value/main-view-model.js

according to latest hello world templates

fix: update ios tests files

---

tests/cli/run/tests/run_tests.py
tests/runtimes/android/android_runtime_tests.py

Remove part of the stack trace which is changing.

Remove part of the stack trace which is changing.

---

core/utils/chrome/chrome_dev_tools.py
core/utils/device/simctl.py
core/utils/run.py

Fix Debug Tests.

---

tests/runtimes/android/android_runtime_tests.py

Add more checks for stack trace after changes in android-runtime.

Add more checks for stack trace after changes in android-runtime.

---

core/settings/Settings.py
tests/docs/test_docs_playgrounds.py
tests/templates/template_tests.py

- Fix http://nsbuild01:8080/build/view/Live%20View/job/live-templates/

fix: live template tests

---

tests/cli/run/tests/run_tests.py

With last commits there are small differences in some logs on run

fix: update run logs

---

tests/cli/create/test_install.py
tests/cli/preview/templates/hello_word_js_tests.py
tests/cli/run/tests/run_tests.py

- Refactor tns install tests
- Fix `test_361_tns_run_ios_on_folder_with_spaces`
- Fix: `test_240_tns_preview_android_verify_plugin_warnings`

chore: fix tests after changes in migrate command

---

assets/runtime/android/files/android-runtime-1347/AndroidManifest.xml
assets/runtime/android/files/android-runtime-1426/AndroidManifest.xml
assets/runtime/android/files/android-runtime-1426/app.js
assets/runtime/android/files/android-runtime-1426/main-view-model.js
tests/runtimes/android/android_service_tests.py

Add tests for intent service for android https://github.com/NativeScript/android-runtime/issues/1426

Add tests for intent service for android

---

assets/runtime/debug/files/console_log/main-view-model.js
core/utils/chrome/chrome_dev_tools.py
tests/cli/debug/test_debug_js.py

https://githubcom/NativeScript/android-runtime/issues/1302

Add test for console log with arabic symbols in debug. 

---

core/utils/device/device.py
tests/runtimes/android/android_runtime_tests.py
tests/runtimes/android/android_service_tests.py

fix test test_204_test_foreground__intent_service_without_oncreate_method_is_working_api28.

fix test test_204_test_foreground__intent_service_without_oncreate_method_is_working_api28.

---

products/angular/ng.py
products/nativescript/tns_assert.py
tests/code_sharing/migrate_web_tests.py
tests/code_sharing/ng_new_tests.py
tests/code_sharing/test_ng_generate_e2e.py

Address changes introduced by https://github.com/NativeScript/nativescript-schematics/pull/220

fix: schematics tests

---

tests/cli/debug/test_debug_js.py

Fix python 3 debug tests.

---

tests/code_sharing/test_ng_generate_e2e.py

Address changes introduced with latest commits in schematics.

fix: tests for ng g during tns run

---

core/settings/Settings.py

https://github.com/NativeScript/nativescript-schematics/pull/237 should resolve https://github.com/NativeScript/nativescript-schematics/issues/234
=> Use @angular/cli@latest again.

chore: rollback hard coded @angular/cli@8.1

---

run_common.py

Fix windows PRs.

---

tests/runtimes/android/android_runtime_tests.py

fix android runtime tests

---

data/changes.py
products/nativescript/tns.py
tests/cli/test/test_test.py

1. add new unit tests with ts projects
2. add livesync changes

feat: added new ts tests and livesync changes

---

tests/runtimes/ios/ios_runtime_tests.py

https://github.com/NativeScript/ios-runtime/pull/1180

fix: tests beacuse of chnages in logging

---

core/utils/assertions.py
core/utils/regex_assert.py
core_tests/unit/utils/regex_assert_tests.py
tests/runtimes/android/android_runtime_tests.py
tests/runtimes/android/error_activity_tests.py

Add regex assert and test for it.

Add regex assert and test for it.

---

core/utils/version.py

fix for a split of version. When using version 10 it wasn't work

fix: change split of version

---

tests/runtimes/android/android_runtime_tests.py

since there are differences in the stack trace log when api is 23 or 28.29 the test need to be updated so it can assert for api28/29 as well

feat: add different regex for api28/29

---

tests/perf/app_size/test_app_size.py

App size increased by adding new architecture in Android runtime.

chore: fix app size tests

---

SETUP.md

libs are need for device tests

feat: add libs

---

core/settings/Settings.py

Change switch for api levels.

---

tests/runtimes/android/error_activity_tests.py

Fix tests for error activity for api29

Fix tests for error activity for api29.

---

data/sync/hello_world_js.py

We rearranged  the changes we do on sync in preview and now asserts need to be updated too

fix: fix asserts in preview sync

---

tests/cli/run/tests/run_tests.py

LaunchImage.launchimage is deprecated

fix: change folder LaunchImage with LaunchScreen

---

core/utils/chrome/chrome_dev_tools.py

name of 'Add expression' button is changed to 'Add watch expression'

fix: button name of add expression

---

tests/perf/data.json
tests/perf/tooling/build_perf_tests.py
tests/perf/tooling/doctor_perf_tests.py

- Do not test incremental prepare and skip prepare.
- Update values.

chore: do not test incremental prepare and skip prepare

---

tests/perf/app_size/test_app_size.py

app size is different because: https://github.com/NativeScript/nativescript-app-templates/pull/92

fix: change app size

---

tests/runtimes/android/android_runtime_tests.py

Change tests tns-core-modules dependency.

Change tests tns-core-modules dependency.

---

tests/code_sharing/migrate_web_tests.py

The text in the default ng project have changed

fix: change text for default ng project

---

assets/runtime/ios/files/ios-runtime-1203/main-view-model.js
assets/runtime/ios/files/ios-runtime-1203/src/MyClass.h
assets/runtime/ios/files/ios-runtime-1203/src/MyClass.mm
assets/runtime/ios/files/ios-runtime-1203/src/module.modulemap
tests/runtimes/ios/ios_runtime_tests.py

related to [this issue](https://github.com/NativeScript/ios-runtime/issues/1203) and this [PR in ios-runtime](https://github.com/NativeScript/ios-runtime/pull/1204)

feat: add test for using Objective C++ files

---

assets/runtime/android/files/android-runtime-1119/package.json
assets/runtime/android/files/android-runtime-1235/package.json
assets/runtime/android/files/android-runtime-1368/package.json
assets/runtime/android/files/android-runtime-1409/package.json
assets/runtime/android/files/android-runtime-961/package.json

so `"markingMode": "none"` like it is in the templates

fix: update package.json files

---

core/settings/Settings.py
core_tests/e2e/core/test_devices.py

simulator 13.0 is not available in xcode11. Update sim to 13.1

chore: update sim to 13.1

---

core/utils/device/simauto.py
core_tests/e2e/core/test_simauto.py

- Make `Simauto` compatible with iOS 13.
- Add test for it

feat: make simauto compatible with iOS13

---

tests/cli/run/templates/master_detail_ng_tests.py

this set builds with snapshot on windows. Add start and stop docker

fix: add start and stop docker

---

tests/code_sharing/ng_new_tests.py

Need to start and stop docker for code sharing  tests too.

fix: codeshare with docker

---

assets/runtime/android/files/android-runtime-1119/app.js
assets/runtime/android/files/android-runtime-1119/java/main-view-model.js
assets/runtime/android/files/android-runtime-1119/javascript/main-view-model.js
assets/runtime/android/files/android-runtime-1119/main-page.js
tests/cli/run/templates/master_detail_ng_tests.py
tests/runtimes/android/android_runtime_tests.py

https://github.com/NativeScript/android-runtime/issues/1445
Add javascript uncaught error case and modify current java error test.

Add javascript uncaught error case and modify current java error test.

---

tests/runtimes/android/android_runtime_tests.py
tests/runtimes/ios/ios_runtime_tests.py

also increase timeout for waiting of logs in ios test that fails from time to time because of not enough time

chore: update logs because of usage of scoped packages

---

core/settings/Settings.py
data/changes.py
data/const.py
data/sync/hello_world_js.py
data/sync/hello_world_ng.py
products/nativescript/app.py
products/nativescript/tns_assert.py

Do not merge!!!!! Work in progress
Updated:
Smoke tests
Templates tests
Not updated:
Vue tests
every test that make change outside live sync workflow methods

chore: update to new templates

---

data/templates.py
tests/templates/template_tests.py

- Remove doctor templates.
- Add Tab Navigation Vue template.

chore: remove doctor templates

---

data/sync/master_detail_vue.py

Appium is restarting the app when attaching to it. This is causing failures in cli livesync tests.
Workaround is for iOS to make initial run and after it start the actual test

fix: vue tests with appium

---

assets/runtime/android/files/filtering/android/with_usage/main-view-model.js
assets/runtime/android/files/filtering/android/with_usage/native-api-usage.json
assets/runtime/android/files/filtering/android/without_usage/main-view-model.js
assets/runtime/android/files/filtering/android/without_usage/native-api-usage.json
assets/runtime/android/files/filtering/ios/with_usage/main-view-model.js
assets/runtime/android/files/filtering/ios/with_usage/native-api-usage.json
assets/runtime/android/files/filtering/ios/without_usage/main-view-model.js
assets/runtime/android/files/filtering/ios/without_usage/native-api-usage.json
assets/runtime/android/files/filtering/plugin/android/native-api-usage.json
assets/runtime/android/files/filtering/plugin/ios/native-api-usage.json
assets/runtime/android/files/filtering/src/index.js
assets/runtime/android/files/filtering/src/package.json
tests/runtimes/android/android_plugins_tests.py
tests/runtimes/ios/ios_runtime_tests.py

Add filtering feature tests.

---

assets/runtime/android/files/filtering/src/platforms/android/native-api-usage.json
assets/runtime/android/files/filtering/src/platforms/ios/native-api-usage.json

Add missing folder for filtering tests.

Add missing folder for filtering tests.

---

assets/runtime/android/files/filtering/src/platforms/android/native-api-usage.json
assets/runtime/android/files/filtering/src/platforms/ios/native-api-usage.json

Merge master in release

---

assets/runtime/android/files/android-runtime-1571/app.gradle
assets/runtime/android/files/android-runtime-1571/main-page.js
tests/runtimes/android/abi_split_with_snapshot_tests.py
tests/runtimes/android/android_app_gradle_tests.py

Add test for issue 1571. Change NDK version in snapshot tests.

Add test for issue 1571. Change NDK version in snapshot tests.

---

.pylintrc
core/utils/device/adb.py
tests/runtimes/android/android_runtime_tests.py
tests/runtimes/android/android_service_tests.py

Fix Api29 tests. Fix changing of time zone tests. increase the time for waiting an emulator.

Fix Api29 tests. Fix changing of time zone tests. increase the time for waiting an emulator.
