- core/settings/Settings.py
Refactor package variables to match the one we already use on CI.
Feature:
Allow usage of NG CLI nighly builds when `export ng_cli=angular/cli-builds`
> refactor: package variables to match existing CI

- .travis.yml
- README.md
- tests/apps/apps_tests.py
- tests/code_sharing/migrate_web_tests.py
- tests/code_sharing/ng_new_tests.py
- tests/perf/build/build_perf_tests.py
- tests/perf/build/create_perf_tests.py
- tests/perf/build/platform_add_perf_tests.py
Fix lint on code sharing and perf tests.
> chore: fix non cli tests

- products/nativescript/tns_assert.py
- tests/code_sharing/ng_new_tests.py
New:
- Add theme parameter on TnsAsserts.created()
Fixed:
-  Schematics tests where project is created with out styling
> feat: add theme parameter on TnsAsserts.created()

- products/nativescript/tns_assert.py
- tests/code_sharing/ng_new_tests.py
Introduce `webpack` param in TnsAssert.created().
Fix code sharing tests.
> feat: add webpack param to TnsAssert.created()

- core/utils/file_utils.py
- core_tests/utils/image_tests.py
We have some failures on Windows with Python3:
```
Traceback (most recent call last):
File "C:\Python37\lib\unittest\case.py", line 59, in testPartExecutor
yield
File "C:\Python37\lib\unittest\case.py", line 615, in run
testMethod()
File "C:\Jenkins\workspace\master-cli-templates-windows\tests\cli\run\templates\hello_word_js_tests.py", line 62, in test_200_run_android_bundle
sync_hello_world_js(self.app_name, Platform.ANDROID, self.emu, bundle=True)
File "C:\Jenkins\workspace\master-cli-templates-windows\data\sync\hello_world_js.py", line 20, in sync_hello_world_js
bundle=bundle, hmr=hmr, uglify=uglify, aot=aot, snapshot=snapshot)
File "C:\Jenkins\workspace\master-cli-templates-windows\data\sync\hello_world_js.py", line 77, in __sync_hello_world_js_ts
Sync.replace(app_name=app_name, …
```
> fix: encoding issues on systems with python3

- data/legacy_app.py
- tests/cli/regression/test_js_regressions.py
- tests/cli/regression/test_ng_regressions.py
- tests/cli/smoke/smoke_tests.py
Migrate regression tests:
https://github.com/NativeScript/nativescript-cli-tests/tree/master/tests/regression
Changes that happened during migration:
- Tests backward compatiblity with 4.2 (instead of 4.1)
- Generate 4.2 app with CLI under test (do not bring old project with tests).
> feat: migrate regression tests

- core/base_test/tns_test.py
- tests/cli/misc/autocomplete_tests.py
- tests/cli/misc/error_reporting_tests.py
- tests/cli/misc/misc.md
- tests/cli/misc/pacakge_manager_tests.py
- tests/cli/misc/setup_tests.py
- tests/cli/misc/version_tests.py
Migrated tests:
- autocomplete
- error reporting
- setup
- version
Features in core:
- Fix get class name
- Enable creating test classes based on TnsTests without specifying setUp and tearDown methods
How tests was looking before:
```
class MyTestClass(TnsTest):
@classmethod
def setUpClass(cls):
TnsTest.setUpClass()
def setUp(self):
TnsTest.setUp(self)
def tearDown(self):
TnsTest.tearDown(self)
@classmethod
def tearDownClass(cls):
TnsTest.tearDownClass()
def test_hello(self):
pass
```
Example how simple test can look like now (and hooks in base class are still executed):
```
class MyTestClass(TnsTest):
def test_hello(self):
pass
```
> feat: migrate misc tests

- core/utils/device/device_manager.py
- core/utils/file_utils.py
- core_tests/device/adb_tests.py
- tests/runtimes/android/error_activity_tests.py
- tests/runtimes/android/todo.md
- tests/runtimes/ios/todo.md
Feat:
- Use emulator snapshot named `clean_boot` (if available)
Fix:
- File.repalce() will now fail if old tests is not available in file
Added Tests:
- Error activity tests
> feat: use emulator snapshots

- .travis.yml
- HINTS.md
- README.md
- core/base_test/tns_run_android_test.py
- core/base_test/tns_run_ios_test.py
- core/base_test/tns_run_test.py
- core/utils/device/simctl.py
- core_tests/e2e/core/test_base_tns_run_test.py
- data/sync/hello_world_ng.py
- tests/cli/run/templates/hello_word_js_tests.py
- tests/cli/run/templates/hello_word_ts_tests.py
- tests/cli/run/templates/hello_world_ng_tests.py
- tests/cli/run/templates/master_detail_ng_tests.py
- tests/cli/smoke/smoke_tests.py
**Base Test Classes**
Introduce new base test classes:
- Base `TnsRunTest` which will start emulator and simulator (only on macOS).
- Base `TnsRunAndroidTest` which will start emulator only.
- Base `TnsRunIOSTest` which will start simulator only.
The idea:
- Remove boilerplate code from setup/teardown of tns tests
**Simctl**
Introduce new methods:
- get list of installed apps
- terminalte all apps
- uninstall all apps
The idea:
- Uninstall all apps before class
- Terminate all apps before each test (to be sure we do not check old screen)
> feat: introduce base TnsRunTest

- .travis.yml
- README.md
- core/base_test/tns_test.py
- scripts/test.sh
Fix:
- Get test class name (it was failing when test do not derive TnsTest directly)
```
Logs Before:
TEST CLASS:  TnsRunTest (base class name)
```
```
Logs Now:
TEST CLASS:  <the-real-class-name>
```
Refactor:
- Move all the commands executed on Travis CI in single script so it is easier to run locally
- Refer the script in README.md (and reduce its size)
> fix: get test class name

- data/legacy_app.py
- tests/cli/regression/test_js_regressions.py
- tests/cli/regression/test_ng_regressions.py
Fix regression tests:
- Do not build with webpack on Windows 
Notes: Will further investigate, when run manually it pass, when executed with `run` method it hangs.
- Use older version of iOS (older modules are released before latest iOS)
> fix: regression tests

- core/utils/device/simctl.py
- tests/cli/run/device/device.py
Test for https://github.com/NativeScript/nativescript-cli/pull/4359
> test: add test for cli pr 4359

- core/utils/device/adb.py
- core/utils/device/device.py
Do not keep temp images when we do not need them.
> fix: reduce artifacts generated during test run

- products/nativescript/tns_logs.py
Removing array members dynamically while iterating over 'string_list' in the wait_for_log method causes changes in the array length and members and some strings are missed during the for loop. 
You can see that  in some of the test results: 
```
13:00:59 13:00:58 TAP found on Emulator-Api23-Default.
13:00:59 13:00:58 taps left found on Emulator-Api23-Default.
13:00:59 13:00:58 'Preparing project...' found.
13:00:59 13:00:58 'Successfully transferred main-page.xml' found.
13:00:59 13:00:58 'Successfully synced application org.nativescript.TestApp on device' found.
13:00:59 13:00:58 Log contains: ['Project successfully prepared (Android)', 'Refreshing application on device']
```
On theory  string_list should be empty if we found all the logs but it's not.  
**Fix:**  
Remove the removing of …
> fix: wait for log method not iterating on  some of the strings

- products/nativescript/tns_logs.py
- products/nativescript/tns_paths.py
Fix:
- Typo in `TnsPaths.get_bundle_id`
- Use `app_id` instead of `app_name` in successfully synced message:
```
'Successfully synced application org.nativescript.{0} on device'.format(app_id))
```
> fix: use app_id in log checks

- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- products/nativescript/tns_logs.py
- tests/cli/regression/test_js_regressions.py
- tests/cli/regression/test_ng_regressions.py
- tests/cli/smoke/smoke_tests.py
Fix smoke and regression tests by settings `instrumented=False` (we do not instrument those apps).
Other:
- Increase timeouts for tns run (up to 300s for NG and 240 for JS/TS, 180 is not enough on some build machines).
- Fix unused variables in TnsLogs
> fix: smoke tests

- data/sync/hello_world_ng.py
- products/nativescript/tns_logs.py
Updated log for specific cases:
When in angular project with hmr changes in app.css file should not cause angular reload. 
When run with env.aot  and change html file it is expected that the file name does not appear as exact string in logs
> fix: logs in angular tests

- core/utils/device/adb.py
- data/sync/hello_world_js.py
- products/nativescript/tns_logs.py
- tests/cli/preview/templates/hello_word_js_tests.py
Fix non osx runs
Remove message from logs, it is changed in latest runtimes
Add method to dismiss simulator alert on ios runs
> fix: preview tests 

- core/base_test/tns_run_test.py
- core/utils/run.py
- requirements.txt
- requirements_darwin.txt
- tests/code_sharing/migrate_web_tests.py
- tests/code_sharing/ng_new_tests.py
Fix:
- Hang when use `run` method on Windows
- Schematics tests are now ready for linux and windows (and based on TnsRunTest)
> fix: schematics tests on Windows

- core/utils/device/adb.py
For some reason mFocusedApp sometime returns nothing.
> fix: detection if emulator booted

- core/utils/chrome.py
- core/utils/device/adb.py
- core/utils/device/device.py
- core/utils/device/simctl.py
- core_tests/unit/product/test_preview_helpers.py
- products/nativescript/preview_helpers.py
- run_common.py
- run_preview.py
- tests/docs/test_docs_playgrounds.py
New:
- Tests for playground samples used in docs
- Introduce new `run_preview.py` to run tests based on preview feature (it copy preview apps in sut folder once before tests)
Refactor:
- Chrome: Add implicit wait of 60sec
- Make `run_adb_command` and `run_simctl_command` public
- Preview.run_url() now takes DeviceInfo object as param (instead of id and platform)
- Escape playground url now happens in `Preview.run_url()` instead of `Preview.get_url()`
Fix:
- Retry `xcrun simctl install` in case of failure (known issue of Xcode 10+)
> feat: tests for playground samples used in docs

- data/changes.py
- data/sync/blank_vue.py
- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- products/nativescript/preview_helpers.py
- products/nativescript/run_type.py
- products/nativescript/tns.py
- products/nativescript/tns_logs.py
- run_common.py
- run_preview.py
- tests/vue/test_vue_preview.py
- tests/vue/test_vue_run.py
New:
- Livesync tests for vue blank template
Refactor:
- Remove `app_type=AppType.NG` param from `sync_hello_world_ng` (it obviously can't be different than NG)
- Remove some `if not app_type == AppType.NG:` checks from TnsLogs (I don't see why we need them)
- Do not check of file name in logs in `__file_changed_messages()` when change is in `*.vue` file
- Pack Template.VUE_BLANK before tests
> feat: add vue tests

- data/changes.py
- data/templates.py
When we execute tests on Xcode9 machines we use iPhone7 simulator.
BMW is not displayed on this device because resolution is lower compared to iPhone X.
Test with `Ford KA` instead of `BMW 5 Series`.
> fix: tests for master detail templates

- tests/docs/test_docs_playgrounds.py
Handle iOS Simulator popup as we do in other tests.
> fix: tests for playground docs

- tests/templates/template_tests.py
This job is failing:
http://nsbuild01:8080/build/view/Live%20View/job/live-templates/
Reason is we look for transfer of vendor.js, while we have thsi in logs:
```
Successfully transferred all files on device 7F78ED16-59F8-4A41-9AD7-58F679CEC6AC.
```
This happens because in this tempalete we have a lot of lazy loaded modules.
> fix: tests for live templates

- core/utils/file_utils.py
- core/utils/npm.py
- core_tests/unit/utils/file_tests.py
- data/sync/hello_world_js.py
- products/nativescript/preview_helpers.py
- run_common.py
- tests/cli/preview/templates/hello_word_js_tests.py
- tests/cli/preview/templates/hello_word_ng_tests.py
- tests/cli/run/templates/hello_world_js_tests.py
- tests/cli/run/templates/hello_world_ng_tests.py
- tests/cli/run/templates/hello_world_ts_tests.py
When we copy app folder we also copy app resources, which cause app rebuilds.
Avoid app rebuilds by copy only file changes.
> refactor: optimize build times

- tests/cli/test/test_test.py
Refactoring:
- Base tests on `TnsRunTest`
Fix:
- Execute tests on Windows (there where no executed previously because of issue with tests with --justlauch on Windows).
> fix: base tests for test command on TnsRunTest

- core/utils/file_utils.py
With python3 print method requires parenthesis.
Use log info method instead to unify runs with different python versions.
> fix pattern_exists method

- core/utils/device/adb.py
- core/utils/device/device_manager.py
- core_tests/unit/product/tns_helpers_tests.py
- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- products/nativescript/tns_logs.py
On Android 7.0+ we do not show logs that happens very early in app live cycle.
For example: no more `ActivityManager: Start proc` on new devices.
Fixes:
- Adb.get_version() now returns float instead of string
- Get version when initialize device with DeviceManager
- Pass `device` to helper methods that get logs
- `__app_restart_messages` now do not return `ActivityManager: Start proc` for new devices
> fix: tns logs for android 7.0+ emulators and devices

- tests/cli/preview/templates/hello_word_js_tests.py
Do not use general method 'preview_hello_world_js_ts' in that test because  it checks for sync messages but we need to verify warning messages before that.
> fix: plugin warnings test

- core/utils/device/device_manager.py
Android `avdmanager` is not compatible with Java 11.
In this case Emulator.is_available() will always retrun true.
> fix: Emulator.is_available() when java11 is used

- assets/runtime/android/files/android-runtime-689/app.gradle
- assets/runtime/android/files/android-runtime-689/app.js
- assets/runtime/android/files/android-runtime-689/main-view-model.js
- tests/runtimes/android/android_app_gradle_tests.py
Add static binding generator for issue https://github.com/NativeScript/android-runtime/issues/689
> Add static binding generator test for issue 689.

- tests/vue/test_vue_run.py
We have known issues with hmr in vue (see https://github.com/nativescript-vue/nativescript-vue/issues/470).
Set `--no-hmr` in vue tests until issue above is fixed.
> chore: set --no-hmr in vue tests for Android

- core/utils/device/adb.py
- core/utils/version.py
We tried to optimize get screneshot by getting it as stream and forward to file on host machines.
This is faster than get screenshot on sdcard and pull it.
We found on some machines and our assumption was it it because of update to macOS Mohave,
It turned out that that is not the reason.
Fall back to old logic that get screenshot on sdcard and pull it.
It is slower, but looks to be more stable.
> chore: remove flaky logic in Adb.get_screen()

- run_common.py
- tests/vue/test_vue_blank_run.py
- tests/vue/test_vue_master_detail_run.py
Template.VUE_MASTER_DETAIL.local_package was null because app is not packed by run_common.py script.
Fix:
- Ensure we pack Template.VUE_MASTER_DETAIL
Refactor:
- Do not explicitly pass bundle and hmr, since they are now used by default
> fix: master-detail-vue tests

- tests/perf/data.json
- First native android build is now much faster because of changes in android runtime.
- master-detail app has much slower initial prepare (still no idea why).
> chore: update perf values

- tests/cli/preview/templates/hello_word_js_tests.py
Do not assert for the logs from the instrumented app. In the cases we use --no-bundle and --no-hmr they are flaky. After 6.0 this logic will be removed anyway.
> fix: failing preview tests

- tests/code_sharing/test_ng_generate_ns.py
After https://github.com/NativeScript/nativescript-schematics/pull/204 we now generate `nsconfig.json` for {N} only apps.
Update tests.
> fix: schematics tests

- products/nativescript/app.py
- products/nativescript/tns.py
When we install dependencies with `--save` it adds them with `^` which may lead to taking wrong version.
`--save --save-exact` should solve the issue.
> fix: save exact version when install dependencies

- products/nativescript/tns_paths.py
- tests/cli/plugin/plugin_cocoapods_tests.py
Plugin cocoapod tests now run with web pack by default.
We cannot assert for plugin files in platforms folder because they are not copied there any more.
To assert if plugin is included we need to require it somewhere in the app and then check the bundle.js and vendor.js files.
> fix: plugin cocoa pod tests

- products/nativescript/tns_logs.py
- tests/cli/run/tests/run_tests.py
add timeout in some tests due to slow machines
remove starter.js from run logs. It is no longer transferred after last changes in web pack
> fix:fix issues with run tests

- assets/template-min/package.json
- core/base_test/tns_test.py
- core/settings/Settings.py
- core/utils/chrome/chrome.py
- core/utils/chrome/chrome_dev_tools.py
- core/utils/device/adb.py
- core/utils/file_utils.py
- core_tests/e2e/core/test_adb.py
- products/nativescript/tns.py
- products/nativescript/tns_assert.py
- products/nativescript/tns_paths.py
- run_common.py
- tests/cli/build/build_tests.py
- tests/cli/plugin/plugin_tests.py
- tests/perf/app_size/test_app_size.py
- tests/perf/runtime/todo.md
**New:**
- Tests for app size of {N} Apps.
- Asserts in Tns.build() that binary exists after build
- Introduce Settings.TEST_OUT_TEMP folder for temp things
- Starting Chrome now happens with user profile in Settings.TEST_OUT_TEMP
- We clean Settings.TEST_OUT_TEMP after in TnsTest.tearDownClass() so we do not attach big artifacts in Jenkins
**Refactoring**
- Get path to apk, app or ipa
- Apply changes caused by item above in all related tests
**Other**
- Update version in min template to 5.4
- Fix typo in chrome_dev_tools.py
> feat: tests for app size

- core/settings/Settings.py
Variables for runtimes are actually `ios` and `android`.
Using `tns_android` and `tns_ios` was leading to always use default versions of runtimes which is `next`.
Using `next` is not correct for PRs against release branch of nativescript-cli.
> chore: change variables for runtimes

- data/sync/hello_world_js.py
- products/nativescript/tns.py
- tests/cli/create/test_init.py
- tests/cli/misc/version_tests.py
1. test_300_install_and_prepare fails because tries to copy app folder from  app in assets that does not exist anymore. Fix: copy app folder from other  test  app
2. test_001_version  fails because when you are with node8, version returns not only version string but warnings also and version.output.split(os.linesep)[-1] is not returning the wright string. Fix: make the main method Tns.version() return the whole output of the command. Assert the version string in the test
3. Preview tests without hmr and bundle often fail. According to logs wait for log timeout expires before the whole execution of the command is finished. Fix: increase timeout for non bundle cases.
> fix: fixes cli tests

- core/utils/chrome/chrome.py
- core/utils/chrome/chrome_dev_tools.py
- requirements.txt
- requirements_darwin.txt
- tests/cli/debug/test_debug_js.py
**Issue Reason**
In latest chrome/driver `actions.double_click(span).perform()` do not cause real double click.
**Impact**
Result is we fail to edit text in elements tab -> failing tests.
**The Fix**
We use `pyautogui` and do real clicks.
In order to do real clicks we need absolute coordiantes of elements so `Chrome.get_absolute_center()` is implemented.
**Notes**
We use strict version of `pyautogui==0.9.39` because as of `pyautogui==0.9.40` it is not compatible with Python 2.
> fix: debug tests

- tests/runtimes/ios/ios_runtime_tests.py
suspect that the test was failing most of the time because of too fast check for stopped process. Update test so that the check is made several times.
> fix: test verification

- core_tests/e2e/products/test_tns.py
- products/nativescript/app.py
1. Update nativescript-vue plugin to next version - the next version is compatible with nativescript@6.0
2. We do not need to update nativescript-dev-typscript by default anymore - set it to False
3. Fix path to webpack update script for projects with space in the name
4. Set update of app in core tests to True, because we cannot build with older versions of webpack
> chore: updates in app update method

- tests/cli/run/tests/run_tests.py
Temporary skip test test_365_tns_run_android_should_respect_adb_errors. On emulator Api28 the UI is crashing  when no space left on device and we try to deploy.
> fix: skip no space left on device test

- tests/runtimes/ios/ios_runtime_tests.py
update is needed because CLI now logs the specific file name instead of `bundle.js`
> fix: update console log assertions messages

- tests/cli/run/tests/run_tests.py
Second run in test should be the same as first without device and provision.
> change run ios without device and provision

- core/utils/npm.py
- data/apps.py
- run_common.py
- tests/code_sharing/migrate_web_tests.py
- tests/code_sharing/ng_new_tests.py
https://github.com/NativeScript/nativescript-schematics/pull/214 require global installation of NG CLI.
Since we do not rely heavily on NG CLI I suggest insalling it globally.
If we encounter troubles we may try local install and custom NPM prefix.
> fix: install NG CLI globally

- core/utils/image_utils.py
- products/nativescript/preview_helpers.py
I notices following error when execute tests on Windows machiens with Python3:
```
Traceback (most recent call last):
File "C:\Python37\lib\unittest\case.py", line 59, in testPartExecutor
yield
File "C:\Python37\lib\unittest\case.py", line 615, in run
testMethod()
File "C:\Jenkins\workspace\master-cli-vue-windows\tests\vue\test_vue_master_detail_run.py", line 49, in test_100_run_android_bundle
sync_master_detail_vue(self.app_name, Platform.ANDROID, self.emu)
File "C:\Jenkins\workspace\master-cli-vue-windows\data\sync\master_detail_vue.py", line 37, in sync_master_detail_vue
device.wait_for_text(text="Ford KA")
File "C:\Jenkins\workspace\master-cli-vue-windows\core\utils\device\device.py", line 99, in wait_for_text
text = self.get_text()
File …
```
> fix: ImageUtils.get_text() on python 3

- core/utils/device/simctl.py
- core_tests/e2e/core/test_devices.py
Problem 1:
- Even if `Simctl.wait_until_boot(simulator_info)` return false, we do not assert it and say iOS Simulator is OK
Problem 2:
- When update Xcode 10.0 to Xcode 10.2 then SDK 12.0 is removed and SDK 12.2 is added
- iOS 12.0 Simulator is still returned by `scrun simctl` but it can not be used, because it is with availability `unavailable`
- In the case above Simctl.is_available() returns `true`
Fixes:
- check ios simulator really available 
- check if ios simulator booted in Simctl.start()
> fix: check ios simulator availability

- tests/cli/run/tests/run_tests.py
Run with clean often fails with error that concurrent build is running on that machine. It looks like the asserts we do, do not wait enough for the previous build to finish. The fix is to add assert that the app is synced and after that run the second build.
> fix: add additional assert in run clean tests

- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- products/nativescript/preview_helpers.py
- tests/cli/preview/templates/hello_word_js_tests.py
Using AppleScript to dismiss simulator alert is a bit flaky. Try making preview test for iOS more stable using device.click() method to dismiss the alert
> fix: replace applescript with device.click() method in preview tests

- core/utils/chrome/chrome.py
On linux machines we also have 25px bar on top.
> fix: hack to respect macOS and Linux default toolbar on top

- core/base_test/tns_test.py
- core/settings/Settings.py
- core/utils/device/adb.py
- core/utils/device/simctl.py
- run_common.py
- tests/templates/template_tests.py
Features:
- Support `api29`
- Support Xcode 11 and iOS 13 (and use iOS 13 by default on Xcode 11).
- Introduce Settings.Packages.TEMPLATES_BRANCH (read it from `templates_branch` env. variable)
Fixes:
- Set correct EnvironmentType if PR detected.
- Tests for live templates now really test live templates (not from GitHub repo).
> feat: support api29 and xcode 11

- core/utils/image_utils.py
After updating some machines to xcode 10.03 text recognition from some images starts failing.
Adjusting dilation and erosion of the image fixed the problems.
> fix: failing text recognition in smoke tests

- tests/cli/device/test_deploy_and_device.py
We deleted `api19` emulators and this made `test_200_list_available_devices` fail.
Use default emulator (api23) in tests.
> chore: fix test_200_list_available_devices

- core/settings/Settings.py
Temporary use @angualr/cli@8.1 because schematics are not compatible with @angualr/cli@8.2
Workaround https://github.com/NativeScript/nativescript-schematics/issues/234
> chore: use Angular 8.1

- tests/cli/debug/test_debug_js.py
The number of a row for a breakpoint is different with a version of chrome 0.76
> fix number of row for debug tests

- assets/runtime/ios/files/ios-runtime-1149/main-view-model.js
- tests/runtimes/ios/ios_runtime_tests.py
https://github.com/NativeScript/ios-runtime/issues/1149
> feat: add test for ios issue 1149

- products/nativescript/tns_assert.py
- tests/cli/preview/templates/hello_word_js_tests.py
Recently we had a bug that files are synced more than once per platform when you preview and livesync to both platforms.
Add method to verify in log that file is synced only once.
Add additional asserts for live sync in preview tests.
> feat: Add assserts for sync in preview tests

- core/settings/Settings.py
- run_common.py
if on windows:
- replace `/tns-dist/` with  `\\telerik.com\distributions\DailyBuilds\NativeScript\`
- replace `/` with  `\`
- In PR for `tns-core-modules` from share replace with `tns-core-modules@next` because of `tns-dist` dependency in the package for widgets
> fix: debug tests on windows when modules are used from local tgz

- tests/market/test_market_playgrounds.py
We close Preview app initial pop up in the beginning of first test but some tests has different names.
> fix: ios closing pop-up

- run_common.py
- tests/cli/build/build_tests.py
Do not clean gradle cache before tests.
Reason for this change:
- Speed up build (gradle wrapper and jars do not downloaded before `tns build/run`)
- More stable jobs (we fail because of timeout limits if we do not clean cache and network is slow)
Notes:
- It may affect build times in perf tests
- It may also affect stability of perf tests (if we do not clean cache it may be in unknown state)
- If it affect stability of perf tests we can rollback clean gradle cache only before perf tests.
> chore: do not clean gradle cache

- tests/cli/run/tests/run_tests.py
#308 
Increase timeout on ios release build. Currently the timeout in wait_for_log method is 1 minute, which is not always enough for the app to build, install and run.
> fix: add timeout to flaky test

- tests/cli/create/create_tests.py
there are changes on console logs text related with help
> fix: change console help text

- tests/cli/run/templates/master_detail_ng_tests.py
Temporary skip test on win due to https://github.com/NativeScript/nativescript-dev-webpack/issues/1021 it is related to issue logged in angular-cli so we have no control when it will be fixed
> fix: temporary skip test on windows

- tests/cli/preview/templates/hello_word_js_tests.py
Fix for test test_210_tns_preview_android_livesync_on_two_emulators
First wait for cli logs and  then assert the device screen, this should make test more stable.
> fix: add additional wait for log

- products/nativescript/tns.py
In tns.test method there is a wait_for_log which by default waits 1 minute. On some machines and angular projects 1 min is not always enough for the app to run on device. Fix: increase timeout to make tests more stable.
> fix: add timeout in test command

- tests/runtimes/android/android_runtime_tests.py
- tests/runtimes/ios/ios_runtime_tests.py
- adding new line in ios log because of changes in ios-runtime - > https://github.com/NativeScript/ios-runtime/pull/1190
- change test to use case_sensitive=False because it's not needed for this test and also to make able to pass on different emulators
> fix: update runtime tests

- tests/cli/device/test_run_on_device.py
`test_100_run_on_all_device` often fails that image is not found on ios simulator screen. When we run on all four devices, we check in the log that app is installed on the real devices by their id, but we don't wait for the simulator id. That might cause that we wait for the image in simulator, but the app is not started there yet. Fix: add sim and emu id in the wait for log too.
> fix: flaky device test

- tests/cli/build/android_app_bundle_tests.py
with new webpack we don't need to set architectures in webpack.config.json
> fix:update aab setup

- tests/cli/plugin/plugin_tests.py
the new version of the plugin: nativescript-socket.ios is broken. 
https://github.com/naderio/nativescript-socket.io/issues/59
> fix: set version of plugin

- tests/cli/debug/test_debug_js.py
App is stuck on splash screen when  `tns debug ios --debug-brk` is executed  and continue debug but current test need additional steps to catch that issue
> fix: add more verification in debug-brk test

- tests/cli/build/android_app_bundle_tests.py
With latest gradle, aab file is generated with different name. Update file name and uncomment fixed logs
> fix: update app bundle path

- tests/cli/create/create_tests.py
git repos of old templates are deleted and tests are failing. Fix: create new testing template repo and  use it in the tests:  https://github.com/NativeScript/test-template-hello-world
> fix: create tests

- assets/runtime/android/files/android-runtime-1463-1459/gradle.properties
- core/utils/file_utils.py
- tests/runtimes/android/abi_split_with_snapshot_tests.py
- tests/runtimes/android/android_plugins_tests.py
- tests/runtimes/ios/ios_runtime_tests.py
add tests for https://github.com/NativeScript/android-runtime/issues/1459 and https://github.com/NativeScript/android-runtime/issues/1463
> Add tests for kotlin and gradle.properties.

- products/nativescript/tns_assert.py
Usually the rc versions of runtimes in npm contain 'rc' as string and we assert that in tests. Lately we often publish runtime and other packaces with versions that don't contain 'rc' string even in rc tag. That causes the tests to fail.
Fix: Remove that check because we are not sure  anymore that rc version of runtimes always contain 'rc' as string.
> fix: asserts for runtime versions

- products/nativescript/tns_assert.py
To check content in apk's Androidmanifest.xml file we use the `apkanalyzer` from the android sdk. But it turned out that there is a bug and it doesn't work on windows. 
Fix: on windows use `apktool` to extract the apk and be able to read the Androidmanifest.xml file.
> fix:check Androidmanifest on windows

- core/utils/os_utils.py
- tests/cli/build/android_app_bundle_tests.py
- tests/cli/build/build_tests.py
- tests/code_sharing/ng_new_tests.py
Schematics tests:
- Do not build with snapshot on macOS Catalina
Refactor:
- Logic to detect macOS Catalina and make it working for hot fix releases of macOS Catalina
> chore: do not build with snapshot on catalina

- core/utils/device/simctl.py
- tests/cli/build/android_app_bundle_tests.py
- tests/cli/run/tests/run_tests_api_28.py
When outputting simulator log we use --level=debug. This leads to very big log files sometimes over 20MB for test set.
1. Fix: use --level=default. This will include default, error and fault log levels, which in the common case should give enough info. With that log level logs are about 2MB not 20MB.
2. Do not start iOS simulator in jobs that test only android
> fix: ios simulator log size

- core/utils/chrome/chrome_dev_tools.py
Debug test often fail on windows with: PyAutoGUI fail-safe triggered from mouse moving to upper-left corner. To disable this fail-safe, set pyautogui.FAILSAFE to False.
This is option of PyAutoGUI we do not use for our tests. Disabling it will avoid that error and should not affect tests in any way.
> fix: disable pyautogui FailSafe option

- data/sync/hello_world_ng.py
Increase timeout in `run_hello_world_ng` in attempt to make `test_320_run_android_release_snapshot_aot_and_uglify` less flaky.
> chore: increase timeout in run_hello_world_ng

- tests/cli/build/android_app_bundle_tests.py
With the last changes, androidNdkPath: "$ANDROID_NDK_HOME is not the last argument in the snapshot section of webpack.config.json, so we need to add comma after it so the file doesn't get corrupted.
> fix: aab tests

- tests/cli/run/tests/run_tests.py
With the last changes in cli and web pack builds are stopping if there is a compilation error and no updates are deployed on the device.
Fix: update logs that are not shown any more. Don't wait for Error in emulator since app won't be deployed broken.
> Fix:run tests 

- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- data/sync/master_details_ng.py
Snapshots are not skipped anymore on windows, we can build with docker now. 
Remove the snapshot skipped check from tests
> fix: check for snapshot skipped message only in 'rc'

- data/sync/hello_world_js.py
- products/nativescript/tns_logs.py
- tests/cli/run/templates/hello_world_js_tests.py
- tests/cli/run/templates/hello_world_ts_tests.py
- tests/cli/run/tests/run_tests_api_28.py
On win we build snapshot with docker, but apparently this is not very fast and the test timeouts before the build is finished.
Fix: add timeout option and increase it for builds on win with snapshot
> fix: increase timeout

- assets/runtime/android/files/android-runtime-1488/app.gradle
- assets/runtime/android/files/android-runtime-1488/app.js
- assets/runtime/android/files/android-runtime-1488/main-view-model.js
- tests/runtimes/android/android_service_tests.py
Add tests for background worker support. https://github.com/NativeScript/android-runtime/issues/1488
> Add tests for background worker support.

- core/utils/docker.py
- tests/perf/app_size/test_app_size.py
When app size tests run on catalina we need to start docker before build
> fix: app size tests with docker

- tests/templates/template_tests.py
http://nsbuild01:8080/build/job/live-templates/ uses a lot of disk space on slaves beause we create 20+ apps (each is 500+ MB when build for both platforms).
Fix:
- Delete app as last step
- If something fails it will not reach the line to delete, so app will be in the workspace to investigate issues.
> chore: cleanup app if test passes

- products/nativescript/tns.py
- tests/cli/build/android_app_bundle_tests.py
With the new workflow build with --aab with snapshot will not require any additional setup. Also --abb will be available for run, debug, test commands also
Keep current tests to test compatibility with the old setup, and add new test to test `tns run --aab --compilesnapshot`
> feat: add aab tests

- data/sync/blank_vue.py
- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- data/sync/master_detail_vue.py
- tests/cli/device/test_run_on_device.py
When livesync with hmr, we verify changes are applied but don't always verify that the app is not restarted which is main hmr feature.
Fix: add asserts that `Restarting application` is not present in logs.
> feat: add more asserts for hmr

- data/sync/blank_vue.py
- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- data/sync/master_detail_vue.py
On windows our waitForLog logic is not working as expected. In result `Restarting application` is found in log from the initial run of the app which is causing fails.
Fix: skip that check for hmr on windows
> fix: win asserts

- tests/cli/build/android_app_bundle_tests.py
Due to this issue: https://github.com/NativeScript/nativescript-cli/issues/5103
when aab test runs on machine with devices the test takes more time to finish, because second build is triggered.
To workaround the problem until the issue is fixed we can wait more time to verify app is deployed.
> fix: aab test

- core/settings/Settings.py
- core/utils/device/device_manager.py
- core/utils/device/simctl.py
Enable not strict iOS simulator versions.
Reason behind this:
- Xcode 11 do not provide older version of iOS13 except latest
- That cause variaty of iOS 13.0, 13.1, 13.2 and so on versions on different machines (it may be machine of external contributor as well)
- We need to give a chance for everyone to run those tests instead of hardcoding fixed version.
> feat: enable not strict ios simulator versions

- core/settings/Settings.py
- data/changes.py
- data/const.py
- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- products/nativescript/app.py
- products/nativescript/tns_assert.py
> chore: merge release in master

- .gitignore
- assets/myCustomTemplate/package.json
- core_tests/unit/utils/wait_tests.py
- data/changes.py
- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- products/nativescript/tns.py
- tests/apps/apps_tests.py
- tests/cli/create/create.md
- tests/cli/create/create_tests.py
- tests/cli/resources/test_resource_generation.py
- tests/cli/resources/test_resource_update.py
- tests/cli/run/tests/run_tests.py
- tests/cli/run/tests/run_tests_api_28.py
- tests/code_sharing/ng_new_tests.py
- tests/code_sharing/test_ng_generate_e2e.py
- tests/code_sharing/test_ng_generate_ns.py
- tests/code_sharing/test_ng_generate_shared.py
- tests/perf/app_size/test_app_size.py
- Fix create tests
- Fix preview tests
- Fix run `run_tests.py` and `run_tests_api_28.py`
- Fix resource update and generate tests
- Fix schematics tests
- Address changes in app size
- Add `Test App` in .gitignore
- Fix flaky unit test causing PRs in this repo to fail.
- Enable `nativescript-marketplace-demo` ignored tests
> chore: address changes caused by new templates

- tests/cli/run/templates/master_detail_ng_tests.py
Ignore tests because of https://github.com/NativeScript/nativescript-ui-feedback/issues/1297
> chore: ignore master details ng tests because of issue

- data/changes.py
- data/sync/blank_vue.py
- data/sync/master_detail_vue.py
- refactor to remove `bundle` (no longer non bundle workflows)
- address changes caused by updates in templates
> chore: fix vue tests

- core/utils/docker.py
On windows docker is very unstable. Lot of errors like: docker: Error response from daemon: error while creating mount source path : mkdir /host_mnt/c: file exists. 
To fix this we could try to keep docker running on windows and not restart it before every run because it seems to be more stable this way.
So on win: run docker only if it is not started and don't kill it after the run
> fix: docker on win

- core/utils/device/simctl.py
- core/utils/version.py
Fix cases when version of iOS is longer, for example 13.2.1.
> fix: cases when iOS version is 3 digits

- core/settings/Settings.py
When preview_folder_path is not passed as env. variable  the fallback is only to /tns-dist but this is not working on windows. 
Fix: set preview falback path according to the os
This will fix failing pr in nativescript-dev-webpack wneh they try to run preview tests on win
> fix: preview fallback path

- core/utils/docker.py
- data/changes.py
- data/const.py
- data/sync/hello_world_ng.py
After the new templates changes some tests that use the live sync workflows are failing in specific cases.
- Sync on iOS device fails with:Css not applied  Expected main color: [203 192 255]  Actual main color: [203 194 245] . On iOS devices version > 12.1 the pink appears with some nuance and is not exactly the same. 
Fix make other change that don't have differences between simulator and device and devices with different versions.
- master detail run on android on windows is failing with Platform specific nested SCSS not applied! The change is actually applied but because of the extensive color of the background and the small resolution of the emulator screen it is not recognized as exactly the same color.
Fix edit the changes so we don't change the whole background with some extensive …
> fix: livesync failures

- core/utils/device/device_manager.py
The issue:
`Simctl.get_max_runtime_version()` returns float and it brakes simulator creation.
The fix:
Cast version to string before replace symbols.
> fix: simulator creation

- core/utils/npm.py
When we get package name with command `npm view {0} dist.tarball` if they are warnings we get them too and the result is not usable as package name
Fix: use silent flag this will return only package name without the warnings
> fix: use npm silent flag

- core/utils/device/device.py
- core/utils/device/device_manager.py
- core/utils/device/emulator_info.py
- core_tests/unit/product/tns_helpers_tests.py
- data/sync/blank_vue.py
- data/sync/hello_world_js.py
- data/sync/hello_world_ng.py
- products/nativescript/preview_helpers.py
- products/nativescript/tns_assert.py
- products/nativescript/tns_logs.py
- tests/cli/preview/templates/hello_word_js_tests.py
- tests/cli/preview/templates/hello_word_ng_tests.py
- tests/runtimes/android/abi_split_with_snapshot_arm64_tests.py
- tests/runtimes/android/abi_split_with_snapshot_arm_tests.py
- tests/runtimes/android/abi_split_with_snapshot_tests.py
There are new console log messages. Changes are related with this PR: https://github.com/NativeScript/nativescript-cli/pull/5098
> fix: device console logs

- data/changes.py
Due to changes in nativescript theme we need to update some changes in master detail template.
> fix: update changes in templates

- products/nativescript/tns.py
Address changes caused by https://github.com/NativeScript/nativescript-cli/pull/5163.
We do not longer build app with hmr enabled when `--justlaunch` is passed.
> fix: debug start test

- .travis.yml
- core/base_test/tns_test.py
- core_tests/unit/utils/file_tests.py
- data/sync/master_detail_vue.py
- products/nativescript/app.py
- requirements.txt
- requirements_darwin.txt
- run_ns.py
- tests/cli/build/android_app_bundle_tests.py
- tests/cli/preview/templates/hello_word_js_tests.py
- tests/cli/preview/templates/hello_word_ng_tests.py
- tests/perf/app_size/test_app_size.py
- tests/vue/test_vue_preview.py
- Update timeouts
- Fix values for app size (for 6.3 we include new css parser in modules and new ios webkit also add ~2%)
- Get host os screenshot on test fail
- Log trace on some tests to debug flakyness
- Minor refactoring
- Fix Travis CI
> chore: fix flaky tests

- core/base_test/tns_test.py
Fix:
- Failing test detection
- Take screenshot of host os
> fix: failing test detection

- core/settings/Settings.py
- tests/cli/run/tests/test_run_scope_package_only.py
Add test for this issue: https://github.com/NativeScript/nativescript-dev-webpack/issues/1089
> test: for issue 1089

- tests/cli/run/tests/test_run_scope_package_only.py
Add tests for https://github.com/NativeScript/nativescript-angular/issues/2058
> chore: run tests with aot and uglify

- tests/runtimes/ios/ios_runtime_tests.py
With latest changes in CLI the `file:///` part of the device logs is replaced by `file: `. Apply the change in the tests.
Changes are described in https://github.com/NativeScript/nativescript-cli/pull/5253
> fix: update expected stacktraces for CLI

- tests/cli/misc/pacakge_manager_tests.py
CLI supports `pnpm` for package-manager and calling `tns package-manager set <invalid value>` should list all supported package managers. This is fixed in CLI, but the expected message in the tests should be fixed as well.
Related to: https://github.com/NativeScript/nativescript-cli/issues/5260 and https://github.com/NativeScript/nativescript-cli/pull/5265
> fix: set correct expected message for package-manager output

- tests/cli/misc/pacakge_manager_tests.py
- tests/cli/misc/package_manager_tests.py
Tests for:
- https://github.com/NativeScript/nativescript-cli/issues/5259
- https://github.com/NativeScript/nativescript-cli/issues/5262
- https://github.com/NativeScript/nativescript-cli/issues/5263
- https://github.com/NativeScript/nativescript-cli/issues/5264
> chore: add tests for package-manager

- tests/perf/app_size/test_app_size.py
Size of ipa increased because of changes in tns-ios@6.4
> chore: update app size values
